name = "PropertyArrays"
uuid = "de04e2eb-689e-4d1a-abcd-f11479f6170a"
authors = ["WooJoongKim0107 <henrikwjkim@gmail.com>"]
version = "0.1.2"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
julia = "1.11"
Distributed = "1.11"
JLD2 = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
